# Generated by Django 5.0.4 on 2024-06-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
