# Generated by Django 5.0.4 on 2024-06-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trip_spots_associated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='spots_associated',
        ),
    ]
