# Generated by Django 5.0.4 on 2024-06-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/'),
        ),
    ]
